<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>default</LangVersion>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\icon.ico</ApplicationIcon>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>
  <PropertyGroup>
    <PublishAot>true</PublishAot>
    <!-- Recommended Avalonia trimming settings for Native AOT -->
    <BuiltInComInteropSupport>false</BuiltInComInteropSupport>
    <TrimMode>link</TrimMode>
  </PropertyGroup>
  <ItemGroup>
    <!-- Preserve Avalonia types for reflection -->
    <TrimmerRootAssembly Include="Avalonia.Themes.Fluent"/>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="11.3.4" />

    <PackageReference Include="Avalonia.ReactiveUI" Version="11.3.4" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.4" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0-rc.1.25451.107" />
    <PackageReference Include="Serilog" Version="4.3.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="ShadUI" Version="0.1.5" />
  </ItemGroup>
  <ItemGroup Condition="'$(Configuration)'=='Debug'">
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.4" />

  </ItemGroup>

  <ItemGroup>
    <TrimmerRootDescriptor Include="Roots.xml"/>
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CertificateViewer.Logic\CertificateViewer.Logic.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Dialogs\MessageBox.axaml"/>
    <UpToDateCheckInput Remove="Dialogs\OpenUrlWindow.axaml"/>
    <UpToDateCheckInput Remove="Dialogs\PasswordBox.axaml"/>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Components\CertificateDetails\CertificateDetailsPanel.axaml.cs">
      <DependentUpon>CertificateDetailsPanel.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Components\MainWindow2\MainWindow2.axaml.cs">
      <DependentUpon>MainWindow2.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Components\CertificateChain\CertificateChainPanel.axaml.cs">
      <DependentUpon>CertificateChainPanel.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Components\TrustStore\TrustStorePanel.axaml.cs">
      <DependentUpon>TrustStorePanel.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Components\Dialogs\OpenUrl\OpenUrlContent.axaml.cs">
      <DependentUpon>OpenUrlContent.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

</Project>